### PR TITLE
Adding Double Crystal Ball function

### PR DESCRIPTION
**Pull request by andreas01060**
Hi, I need to fit a double crystal ball for a project. Hence, this pull request. I think I have added all necessary
lines of codes to accommodate this. 
Thank you

### CODE REVIEW

**Comment by eduardo-rodrigues** [comment]
Hi @andreas01060 and @HDembinski, I just bumped into this old PR. Any hope to get it sorted and merged soon? It's a nice addition.

**Comment by andreas01060** [comment]
Hi @eduardo-rodrigues, I couldn't get it past the tests, so in the end I just cloned my probfit version and added it to my python packages (and it works). I didn't really understand why the tests failed, that's why I abandoned on the PR. When I have some time, I will try again though.

**Comment by henryiii** [comment]
Tests fail because ProbFit does not work with iMinuit > 1.2, I believe. I think we probably should pin the iMinuit version, then try to fix this (and then unpin the version).

**Comment by eduardo-rodrigues** [comment]
Thanks for your reply @andreas01060. Seems @henryiii has found the source of the problem and PR https://github.com/scikit-hep/probfit/pull/89 aims at sorting it out. Fingers crossed ...

**Comment by marinang** [comment]
Hi @eduardo-rodrigues. I have a fork of profit and I modified some stuffs, like in #84, and some additions for future PR (johnsonSU pdf, add constraints to likelihood), but nothing crucial or I don't recall. As you said I have python 3.7 and iminuit 1.3.2.

**Comment by eduardo-rodrigues** [comment]
So you say that with https://github.com/scikit-hep/probfit/issues/84 you actually got the builds OK? If that's the case it would make sense to have a PR with that, to try and fix Travis ...

Cc @henryiii for info.

**Comment by eduardo-rodrigues** [comment]
Hi @andreas01060, can you rebase this PR to resolve the conflicts, now that https://github.com/scikit-hep/probfit/pull/91
 went in?

**Comment by andreas01060** [comment]
Hi @eduardo-rodrigues , I resolved the conflicts, but the check is still failing..

**Comment by marinang** [comment]
The plotting test are failing, because you changed all the plotting test with gaussian with double crystal ball right, in test_plotting.py? I think you let those tests as they were with the gaussian.

**Comment by andreas01060** [comment]
Hi @marinang, yes true , but now it's back to how how it first was: I deleted those changes and put back in the original ones.

**Comment by eduardo-rodrigues** [comment]
That's right, you seem to have replaced tests whereas you should be adding new tests for the double CB. I believe the replacement of tests was in since the first commit.

**Comment by andreas01060** [comment]
Hi sorry for the delay, Is it okay now? I was confused, I thought the various plotting tests should also be applied on any new functions implemented..

**Comment by henryiii** [comment]
Whoever merges this should make sure it's a squash and merge...

**Comment by henryiii** [comment]
Just curious though, can't you just add two crystal ball functions? I believe this even happens at the compiled code level due to Cython's cpdef.

```python
>>> dg = probfit.AddPdf(probfit.crystalball, probfit.crystalball, prefix=['f_','g_'], skip_prefix=['mean', 'sigma'])
>>> probfit.describe(dg)
['x', 'f_alpha', 'f_n', 'mean', 'sigma', 'g_alpha', 'g_n']
>>> dg(10, 1, 2, 10, 2, 1, 1) / 2 
1.0
>>> dg(11, 1, 2, 10, 2, 1, 1) / 2
0.8824969025845955
```

I'd rather have a small set of core elements that can be composed, I think.

**Comment by andreas01060** [comment]
I think this might be just the case from the particular example you give. If you take x such that it's in the tails, I don't think it will work. Also when the alpha and n differ for the two tails, this complicates it more.

**Comment by henryiii** [comment]
With all the examples you've provided, I get identical results to floating point precision. Can you add an example with different values in the two tails to the test?

**Comment by eduardo-rodrigues** [comment]
Henry's suggestion for extra tests is a good one. On the doc side I would suggest that you add this is a double CB of common mean and core resolution (OK, obvious from the signature, but still good to add for clarity).

Otherwise this seems ready to go. Nice.

**Comment by eduardo-rodrigues** [comment]
Thumbs up from me.

**Comment by eduardo-rodrigues** [comment]
Just pinging you @HDembinski, for when you have the time, as this seems ready to go.

**Comment by HDembinski** [comment]
@andreas01060 Thank you for contributing this!

**Comment by andreas01060** [comment]
Thank you all for helping me out! (This was my first time using github, so sometimes it was a bit cryptic for me. )

**Pull request merged**
