### PR TITLE
Adaptation of names to new org

### PR DESCRIPTION
**Pull request by eduardo-rodrigues**
There may be some other little things to fine-tune …

I profited from the occasion to add builds for Python 3.6.

### CODE REVIEW

**Comment by eduardo-rodrigues** [comment]
Thanks for the approval. Let me then merge this at this point, in spite of some tests failing, since the changes are not to any part of code, and it makes the doc more up-to-date.

**Comment by cdeil** [comment]
I'll update https://readthedocs.org/projects/probfit/ to point to the new repo.

**Comment by cdeil** [comment]
RTD is failing: https://readthedocs.org/projects/multinorm/builds/7999821/

If someone is willing to fix this and do minimal maintenance for this package, let me know and I can add you you RTD and PyPI.

**Comment by eduardo-rodrigues** [comment]
BTW, the "documentation" link in the README rather points to https://probfit.readthedocs.io/en/latest/. I do not know which is meant to be used and which one is obsolete … ;-)

**Comment by cdeil** [comment]
Oops, sorry, copy & paste error. Yes, of course this project is  https://probfit.readthedocs.io/en/latest/ on RTD.

**Comment by HDembinski** [comment]
Could you please add me to RTD and PyPI as maintainer for probfit? I don't have time now, but I would like to work on probfit in the future.

**Comment by cdeil** [comment]
> Could you please add me to RTD and PyPI as maintainer for probfit?

Done

> I don't have time now, but I would like to work on probfit in the future.

Thanks!

Just a comment from the sidelines:

Overall I'm not sure if reviving probfit or leaving it dead would be better. It's just something that one person did once, doesn't do many things and also tying modeling / fitting to iminuit and Cython is questionable. A great and modern Python modeling / fitting package should emerge. But I guess absent that project existing, probfit should live on. And who knows, maybe it will grow and flourish.

I think some kind of message on the docs frontpage would be good to have: "Try out probfit, but note that other options for modeling and fitting exist, e.g. https://lmfit.github.io or https://sherpa.readthedocs.io or https://root.cern.ch/roofit".

**Comment by HDembinski** [comment]
Good suggestion. I think people would love something like roofit without the "roo" part. It looks like lmfit is not a full model-building package, but Sherpa looks like a reasonable replacement for roofit at first glance.

Btw, the correct link for lmfit is https://lmfit.github.io/lmfit-py/

**Comment by cdeil** [comment]
As far as I know, lmfit and Sherpa are the most advanced modeling / fitting / parameter estimation packages in Python.

I saw that lmfit is now gaining covar estimation for any likelihood:
https://github.com/lmfit/lmfit-py/pull/506

Sherpa is great. It comes from astronomy, has lots of astro stuff built in, but is also a general modeling / fitting package. However, it does have certain design flaws such as e.g. if you look at https://sherpa.readthedocs.io/en/latest/quick.html#simultaneous-fits you will see:

> For simultaneous fits the same optimisation and statistic needs to be used for each fit (this is an area we are looking to improve)

That is pretty constraining, and not easy to change given their ~ 10 year legacy and existing users requiring API stability.

Also if you try to fit some data with more than one or two dimensions, you will find that N-D support isn't well developed.

Because in Gammapy we need to have per-dataset different fit statistics, and we have a lot of 3D data and models, we now started rolling our own modeling / firting package: https://github.com/gammapy/gammapy/tree/master/gammapy/utils/fitting
Clearly that is not a good thing, there's nothing gamma-ray specific in there, although we do use Astropy Table objects in some parts of the API.

As a tiny effort to create something more general (beyond iminuit or sherpa or Gammapy), I started this a week ago: https://github.com/cdeil/multinorm
It's not an attempt at a modeling / fitting package, just a tiny part of it, a good class to work with the covariance matrix.

If you guys are starting something for modeling / fitting, or just to exchange ideas, I'd be interested. I joined the scikit-hep list just now.

**Pull request merged**
